services:
  # Base de données
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Interface d'administration MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 128M
    restart: unless-stopped

  # Serveur mail de développement
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  # Microservice d'envoi d'emails
  mail-service:
    build: ./mail-microservices
    ports:
      - "8000:8000"
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: contactbenintourisme@gmail.com
      MAIL_FROM_NAME: "KWABO"
      APP_URL: http://localhost:8080
    volumes:
      - ./mail-microservices:/var/www/html
      - ./mail-microservices/vendor:/var/www/html/vendor
    depends_on:
      - mailhog

  # Application principale
  app:
    build: ./app_php
    ports:
      - "8080:80"
    volumes:
      - ./app_php:/var/www/html
    depends_on:
      - db
      - mail-service

  # Service CRON amélioré
  cron:
    build: ./app_php
    command: >
      bash -c "echo '0 0 * * * php /var/www/html/cron/check_subscriptions.php' > /etc/cron.d/cronjob &&
      chmod 0644 /etc/cron.d/cronjob &&
      cron -f"
    volumes:
      - ./app_php:/var/www/html
      - ./app_php/cron:/var/www/html/cron
    depends_on:
      - db
      - mail-service

volumes:
  mysql_data: